import { createAction, createSlice } from "@reduxjs/toolkit";
import { IUser } from "../../type/backend";

export interface UserState {
    isPending: boolean;
    isError: boolean;
    users: IUser[];
    errors: any;
    isCreating: boolean;
    isCreateSuccess?: boolean;
    isEditing: boolean;
    isEditSuccess?: boolean;
    isDeleting: boolean;
    isDeleteSuccess?: boolean;
}

const initialState: UserState = {
    isPending: false,
    isError: false,
    users: [],
    errors: [],
    isCreating: false,
    isCreateSuccess: false,
    isEditing: false,
    isEditSuccess: false,
    isDeleting: false,
    isDeleteSuccess: false,
};

export const logingInPending = createAction<{
    email: string;
    password: string;
}>("logingInPending");

export const logout = createAction("logout");

export const fetchUserPending = createAction("fetchUserPending");
export const fetchUserSuccess = createAction<IUser[]>("fetchUserSuccess");
export const fetchUserFailed = createAction("fetchUserFailed");

export const createUserPending = createAction<{ email: string; name: string }>(
    "createUserPending",
);
export const createUserSuccess = createAction("createUserSuccess");
export const createUserFailed = createAction("createUserFailed");

export const editUserPending = createAction<{
    id: number | undefined;
    email: string;
    name: string;
}>("editUserPending");
export const editUserSuccess = createAction("editUserSuccess");
export const editUserFailed = createAction("editUserFailed");

export const deleteUserPending = createAction<{ id: number }>(
    "deleteUserPending",
);
export const deleteUserSuccess = createAction("deleteUserSuccess");
export const deleteUserFailed = createAction("deleteUserFailed");

export const userSlice = createSlice({
    name: "counter",
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {},
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(fetchUserPending, (state, action) => {
                state.isPending = true;
                state.isError = false;
            })
            .addCase(fetchUserSuccess, (state, action) => {
                state.isPending = false;
                state.isError = false;
                state.users = action.payload;
            })
            .addCase(fetchUserFailed, (state, action) => {
                state.isPending = false;
                state.isError = true;
                state.errors = action.payload;
            })
            .addCase(createUserPending, (state, action) => {
                state.isCreating = true;
                state.isCreateSuccess = false;
                state.isError = false;
            })
            .addCase(createUserSuccess, (state, action) => {
                state.isCreating = false;
                state.isCreateSuccess = true;
                state.isError = false;
            })
            .addCase(createUserFailed, (state, action) => {
                state.isCreating = false;
                state.isError = true;
                state.isCreateSuccess = false;
                state.errors = action.payload;
            })
            .addCase(editUserPending, (state, action) => {
                state.isEditing = true;
                state.isEditSuccess = false;
                state.isError = false;
            })
            .addCase(editUserSuccess, (state, action) => {
                state.isEditing = false;
                state.isEditSuccess = true;
                state.isError = false;
            })
            .addCase(editUserFailed, (state, action) => {
                state.isEditing = false;
                state.isError = true;
                state.isEditSuccess = false;
                state.errors = action.payload;
            })
            .addCase(deleteUserPending, (state, action) => {
                state.isDeleting = true;
                state.isDeleteSuccess = false;
                state.isError = false;
            })
            .addCase(deleteUserSuccess, (state, action) => {
                state.isDeleting = false;
                state.isDeleteSuccess = true;
                state.isError = false;
            })
            .addCase(deleteUserFailed, (state, action) => {
                state.isDeleting = false;
                state.isError = true;
                state.isDeleteSuccess = false;
                state.errors = action.payload;
            });
    },
});

export const {} = userSlice.actions;

export default userSlice.reducer;
