import { createSlice, createAction } from "@reduxjs/toolkit"

export interface CounterState {
    isPending: boolean,
    isError: boolean,
    data: any,
    errors: any
}

const initialState: CounterState = {
    isPending: false,
    isError: false,
    data: [],
    errors: [],
}

export const fetchUserPending = createAction<{ value: number }>("fetchUserPending");
export const fetchUserSuccess = createAction<{ value: number }>("fetchUserSuccess");
export const fetchUserFailed = createAction<{ value: number }>("fetchUserFailed");



export const userSlice = createSlice({
    name: "counter",
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {



    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(fetchUserPending, (state, action) => {

            })
            .addCase(fetchUserSuccess, (state, action) => {

            })
            .addCase(fetchUserFailed, (state, action) => {

            })

    },
})

export const { } = userSlice.actions



export default userSlice.reducer
